#! /bin/sh

bspc config border_width            0
bspc config window_gap              30

bspc monitor -d one two three four

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config ignore_ewmh_focus       false

bspc config pointer_modifier        mod1
bspc config pointer_action1         resize_side

bspc config pointer_action2         move

wmname LG3D
